sudo: required
services:
  - docker
lanugage: python
python:
  - "2.7"
install:
  - sudo apt-get update
  #### Docker:
  - docker build -t superphy/backend:2.0.0 -f Dockerfile-spfy
  - docker build -t superphy/backend-rq:2.0.0 -f Dockerfile-rq
  - docker build -t superphy/backend-rq-blazegraph:2.0.0 -f Dockerfile-rq-blazegraph
  - docker-compose up

  #### miniconda install:
  - cd app/
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  #### Recreate our Conda env for testing
  - conda create -f environment.yml
  - source activate backend
