version: '2'
services:
  web-nginx-uwsgi:
    build:
      context: .
      dockerfile: Dockerfile-spfy
    image: superphy/backend:2.1.0
    ports:
    - "80:80"
    depends_on:
    - redis
    - blazegraph
    volumes:
    - /datastore
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile-rq
    image: superphy/backend-rq:2.0.0
    volumes_from:
    - web-nginx-uwsgi
    depends_on:
    - web-nginx-uwsgi
    restart: always

  worker-blazegraph-ids:
    build:
      context: .
      dockerfile: Dockerfile-rq-blazegraph
    image: superphy/backend-rq-blazegraph:2.0.0
    volumes_from:
      - web-nginx-uwsgi
    depends_on:
    - web-nginx-uwsgi
    restart: always

  redis:
    image: redis:3.2
    restart: always

  blazegraph:
    image: superphy/blazegraph:2.1.4
    ports:
    - "8080:8080"
    volumes:
    - /var/lib/jetty/
    restart: always
