version: '2'
services:
  web-nginx-uwsgi:
    build:
      context: .
      dockerfile: Dockerfile-spfy
    image: backend
    ports:
    - "8000:80"
    depends_on:
    - redis
    - blazegraph
    volumes:
    - /datastore

  worker:
    build:
      context: .
      dockerfile: Dockerfile-rq
    image: backend-rq
    volumes_from:
    - web-nginx-uwsgi
    depends_on:
    - web-nginx-uwsgi

  worker-blazegraph-ids:
    build:
      context: .
      dockerfile: Dockerfile-rq-blazegraph
    image: backend-rq-blazegraph
    volumes_from:
      - web-nginx-uwsgi
    depends_on:
    - web-nginx-uwsgi

  redis:
    image: redis:3.2

  blazegraph:
    image: superphy/blazegraph:2.1.4-inferencing
    ports:
    - "8080:8080"
    volumes:
    - /var/lib/jetty/
