version: '2'
services:
  web-nginx-uwsgi:
    image: superphy/backend:2.0.0
    ports:
    - "80:80"
    depends_on:
    - redis
    - blazegraph
    volumes:
    - /datastore

  worker:
    image: superphy/backend-rq:2.0.0
    volumes_from:
    - web-nginx-uwsgi
    depends_on:
    - web-nginx-uwsgi

  worker-blazegraph-ids:
    image: superphy/backend-rq-blazegraph:2.0.0
    volumes_from:
      - web-nginx-uwsgi
    depends_on:
    - web-nginx-uwsgi

  redis:
    image: redis:3.2

  blazegraph:
    image: superphy/blazegraph:2.1.4
    ports:
    - "8080:8080"
    volumes:
    - /var/lib/jetty/
