version: '2'
services:
  web-nginx-uwsgi:
    image: nitzoy/backend-production:latest
    ports:
    - "80:80"
    depends_on:
    - redis
    - blazegraph
    volumes:
    - /datastore

  worker:
    build: .
    image: backend-rq
    container_name: rq_worker
    volumes_from:
      - web-nginx-uwsgi
    depends_on:
    - web-nginx-uwsgi

  redis:
    image: redis:3.2

  blazegraph:
    image: superphy/blazegraph:2.1.4
    ports:
      - "8080:8080"
